### ISSUE TITLE
Installation with npm gives code EINTEGRITY

### ISSUE THREAD

**Issue by smac89** [mdbootstrap/Angular-Bootstrap-with-Material-Design#1]
Hi, thanks for the awesome package. I have a problem when installing with npm. I get the following output:

``` bash
$ npm install --save angular-bootstrap-md
npm ERR! code EINTEGRITY
npm ERR! sha512-OLsh6pBJZBnwBWyBjqn7DCzlIrp3/k1XG92bbHj4BQrItCcMvPY6weq6ak8ZVlj7yQgDmGAvnqIH9rAsiEWSXw== integrity checksum failed when using sha512: wanted sha512-OLsh6pBJZBnwBWyBjqn7DCzlIrp3/k1XG92bbHj4BQrItCcMvPY6weq6ak8ZVlj7yQgDmGAvnqIH9rAsiEWSXw== but got sha512-Ew+xvOLLdG4SuK4mKnr5kp7XMKtiV8JdmZjuvgAZsZ6RAr+/z6fgyke9D1OLuW41SRHhbzfBuQuOwOCb5WMEDQ==. (2490070 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ghekis/.npm/_logs/2017-06-27T18_57_12_216Z-debug.log
```

I'm not sure if it has to do with just npm itself or with the way the file has been packaged when shipped. Perhaps it was modified after upload?

**Comment by AdrianSaw** [comment]
Hello,
I've read quite a lot about it and found two answers for it:

1. Clean your npm cache ( didn't work for me but maybe it will help anyone else )
`rm ./package-lock.json`
`rm ./node_modules`
`npm cache clear --force`

2. Downgrade you npm because the problem only exist on newest version. 
everything works fine on 4.6.1 version. To do so just write:
`npm install npm@4.6 -g`

I won't give up so easly and I hope that I will find better answer for this.

**Comment by jonfulk** [comment]
Same issue

**Comment by Spiderbezno** [comment]
Some Issue

**Comment by smac89** [comment]
@AdrianSaw 
Perfect! That seems to have done it

**Comment by alexandre-vasconcellos** [comment]
I don't think this is the solution. You should correct what is wrong, and not install an older version of npm.

**Comment by enitesh** [comment]
@AdrianSaw Thanks. Your solution worked for me. The issue was driving me nuts.
