### ISSUE TITLE
 ERROR in Illegal State: referring to a type without a variable "name":"WavesDirective","members":[]}

### ISSUE THREAD

**Issue by maximegheraille** [mdbootstrap/Angular-Bootstrap-with-Material-Design#130]
### Expected behavior
production build working without errors
### Actual behavior
 ERROR in Illegal State: referring to a type without a variable
### Your working environment and MDB version information
Technology: Angular
MDB Version: 8.5.0
### Resources (screenshots, code snippets etc.)
his is the errorThis is the file where the erros comes from 
![1](https://user-images.githubusercontent.com/32335849/68230893-4bcace80-fffa-11e9-972c-dbb552317e21.jpg)
![2](https://user-images.githubusercontent.com/32335849/68230894-4c636500-fffa-11e9-84f6-c369d1f819b3.jpg)
 package.json
![3](https://user-images.githubusercontent.com/32335849/68230895-4c636500-fffa-11e9-8417-452a28f0822a.jpg)
angular.json.
![4](https://user-images.githubusercontent.com/32335849/68230896-4c636500-fffa-11e9-8a5b-ecf66270e470.jpg)

**Comment by idzark** [comment]
I'm going to close this because I already answered on our support forum: https://mdbootstrap.com/support/angular/error-in-illegal-state-referring-to-a-type-without-a-variable/

If anyone have the same problem, please try to downgrade your angular/cli and angular-devkit/build-angular packages versions to:

```
    "@angular-devkit/build-angular": "~0.802.0",
    "@angular/cli": "~8.2.2"
```
