### ISSUE TITLE
Charts.js not found

### ISSUE THREAD

**Issue by JeeDragon** [mdbootstrap/Angular-Bootstrap-with-Material-Design#3]
I got this error and I couldn't find anything about it. I followed the npm steps and then did ng serve and got this error in a new project.

ERROR in ./~/angular-bootstrap-md/charts/chartDirective.js
Module not found: Error: Can't resolve 'chart.js' in '\node_modules\angular-bootstrap-md\charts'
 @ ./~/angular-bootstrap-md/charts/chartDirective.js 2:0-33
 @ ./~/angular-bootstrap-md/charts/index.js
 @ ./~/angular-bootstrap-md/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by editt-editt** [comment]
Hi, 

I would like to ask you some questions in order to help you.

1. Did you download our repository?
2. Have you created a project with Angular CLI?
3. If you created a custom project, have you modified angular-cli.json in any way (more than what is said in our instruction)? 

Thanks for the feedback!

**Comment by JeeDragon** [comment]
I followed the updated information on commit 3cb42562bc82b591eca877a0100b9b4dc2f74d03 and was able to get the charts.js problem solved and everything is working nicely now. Thanks!
