### ISSUE TITLE
Carousel Animation Is A Lot Smoother On Demo Page Than Project Source

### ISSUE THREAD

**Issue by LocDaiNguyen** [mdbootstrap/Angular-Bootstrap-with-Material-Design#45]
The animation on the demo page https://mdbootstrap.com/angular/advanced/carousel is a lot smoother than the one in the project source. In the project source the animation is more of a flash between transitions. The one on the demo page transition smoothers. What is the difference?

**Comment by Bloodcast69** [comment]
Hello LocDaiNguyen,

It is caused by this, that in our documentation [animation] is set to 'fade'. But from default, documentation code has [animation] set to slide.

If you want to have that smooth fade animation, just add [animation]="'fade", and in /assets/scss/mdb/free/_carousel-basic.scss you can modify transition-duration value ( line 31) to make animation more/less smoother.

Best Regards,
Damian
