### ISSUE TITLE
Missing Bootstrap Javascript for JS features like tooltips

### ISSUE THREAD

**Issue by Weber-D** [mdbootstrap/Angular-Bootstrap-with-Material-Design#71]
I followed the quick start guide from https://mdbootstrap.com/angular/5min-quickstart/ and noticed that the Javascript files from Bootstrap are required as well as jQuery for some features like tooltips. So I installed jQuery and want to include the corresponding js files from Bootstrap. The quick start guide show how to include thirt party modules like hammer.js or Chart.js and the `bootstrap.css` located at `"node_modules/angular-bootstrap-md/scss/bootstrap/bootstrap.scss"`.

However, it seems that we don't have the js from Bootstrap. I couldn't find them in the latest release. My only workaround is to look at `bootstrap.css` to get the version from the header

```
/*!
 * Bootstrap v4.0.0 (https://getbootstrap.com)
 * Copyright 2011-2018 The Bootstrap Authors
 * Copyright 2011-2018 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
```
And install the specified version (here 4.0) by hand using npm. So we can include the js files from there. This is suiteable, but it would be nice if you can bundle the Bootstrap js file as well as the scss one and mention it in your documentation.

**Comment by Bloodcast69** [comment]
Dear @Weber-D,
please note, that you shouldn't use jQuery or plain javascript in your angular applications. 

Everything should be written with Typescript. And we did it in same way. 

You don't have to add jQuery to your project, because our components got logic written by our team in Typescript - so they are ready to use. 

Just clone this repo and install it like 5min-quickstart shows, and you're ready to create amazing projects using our MDB Angular.

Best Regards,
Damian

**Comment by dawidadach** [comment]
Dear @Weber-D , you can find tooltips here: 
https://mdbootstrap.com/angular/advanced/tooltip/
